"バックアップファイル及びスワップファイルを作成するかどうか。不要なファイルの残留を無くすために、作成しないよう設定"
set nobackup   
set noswapfile 

"改行時、自動で最適なインデントが挿入される"
set smartindent

"使用する文字コードにUTF-8を指定"
set fenc=utf-8

"現在開いている未編集ファイルが外部で編集された場合に再読込を行う。ログファイルなどを Vim で見る際、追記・編集が自動で反映されるようになる"
set autoread

"編集したファイルが未保存であっても、別のファルを開けるようにする"
set hidden

"シンタックスハイライトを有効にする"
syntax enable

"長い業の折返しを無効化する"
set nowrap

"256 色カラーを使用する"
set t_Co=256

"行番号を表示する"
set number

"カラーテーマをelflordに設定する"
colorscheme elflord

"検索にヒットした部分をハイライトする"
set hlsearch

